name: Deploy on Fleek

on:
  push:
    branches: [ "v2" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
      NEXT_PUBLIC_DYNAMIC_API_KEY: ${{ secrets.NEXT_PUBLIC_DYNAMIC_API_KEY }}
  
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4 
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.2        
        cache: 'pnpm'

        
    - name: Install dependencies
      run: pnpm install

    - name: Install Fleek CLI
      run: pnpm i -g @fleek-platform/cli

    - name: Set environment variables
      run: pnpm set-env:bartio
      
    - name: Build all projects 
      run: NEXT_PUBLIC_HOST="ipfs" pnpm run build --filter=lend --filter=perp --filter='./packages/*'
      
    - name: Deploy Berps
      run: cd apps/perp && fleek sites deploy

    - name: Deploy Bend
      run: cd apps/lend && fleek sites deploy
