
name: Test static build on IPFS

on:
  workflow_dispatch:
  pull_request:
    branches:
      - v2
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4 

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.2
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      
    - name: Set environment variables
      run: pnpm set-env:bartio

    - name: Build all projects 
      env: 
        PERPS_OCT_KEY: ${{ secrets.PERPS_OCT_KEY }}
        # CHARTING_ACCESS_TOKEN: ${{ secrets.CHARTING_ACCESS_TOKEN }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      run: NEXT_PUBLIC_PERPS_TRADINGVIEW_ENABLED="false" NEXT_PUBLIC_HOST="ipfs" pnpm run build --filter=lend --filter=perp --filter='./packages/*'
     